version: "3"

services:

    ## Elasticsearch container
    elasticsearch:
        container_name: "elasticsearch-pruebas"
        image: elasticsearch:7.2.0
        ports:
            - 9200:9200
        environment:
            - discovery.type=single-node


    ## Kibana container
    kibana:
        container_name: "kibana-pruebas"
        image: kibana:7.2.0
        depends_on:
            - elasticsearch
        ports:
            - 5601:5601
        links:
            - "elasticsearch"
        environment:
            - ELASTICSERACH_HOSTS=http://elasticsearch:9200


    ## Filebeat for test app
    filebeat:
        container_name: "filebeat-pruebas"
        image: docker.elastic.co/beats/filebeat:7.2.0
        user: root
        depends_on:
            - elasticsearch
        links:
            - "elasticsearch"
        volumes:
            - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
            - ./logs:/usr/share/logs:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        command: filebeat -e -strict.perms=false

    
