filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false


#-------- Input logs with correspondant configuration. With json.key the json inputs are processed as separated fields
# on elasticserach, allowing you select on kibana those fields as columns
filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/logs/out.log
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: log       

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
- add_cloud_metadata: ~



#-------- Setup the index name template. After that, create an index following the pattern!
setup.template.name: "louzao"
setup.template.pattern: "louzao-*"
setup.template.fields: ./fields.yml

#-------- Put the correspondant pattern of your file on index field. Must match the setup.template.pattern.
output.elasticsearch:
  hosts: ["elasticsearch-pruebas:9200"]
  index: "louzao-macarrones"
  indices:
    - index: "louzao-macarrones"


